### ISSUE TITLE
Doesn't build with dart 2.13 (Flutter 2.2)

### ISSUE THREAD

**Issue by tvh** [abner/flutter_js#42]
The following function was removed in dart 2.13 and is used in the jscore-bindings:

```
@Deprecated('Hold on to the pointer backing a struct instead.')
Pointer<T> get addressOf => _addressOf as Pointer<T>;
```

**Comment by cacard** [comment]
here is my error when compile on flutter 2.2:

/C:/flutter_windows_2.2.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_js-0.2.3+0/lib/javascriptcore/jscore/js_class.dart:16:70: Error: The getter 'addressOf' isn't defined for the class 'JSClassDefinition'.
 - 'JSClassDefinition' is from 'package:flutter_js/javascriptcore/binding/js_object_ref.dart' ('/C:/flutter_windows_2.2.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_js-0.2.3+0/lib/javascriptcore/binding/js_object_ref.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      : this.pointer = JSObjectRef.jSClassCreate(definition.create().addressOf);

**Comment by magnusfaltinbooks** [comment]
https://github.com/xuelongqy/flutter_jscore have updated its code where they removed the methodcall to addressOf

**Comment by vinner2606** [comment]
Please fix this issue in library as soon as possible.

**Comment by abner** [comment]
fixed on flutter_js 0.5.0+0

**Comment by gzlock** [comment]
🎉
waiting for you release the 0.5.0+0 to repository

**Comment by abner** [comment]
> waiting for you release the 0.5.0+0 to repository

it was already published to pub.dev, but i added the tag on github also

**Comment by gzlock** [comment]
123123

> > waiting for you release the 0.5.0+0 to repository
> 
> it was already published to pub.dev, but i added the tag on github also

![image](https://user-images.githubusercontent.com/2311740/121778393-49aef580-cbc9-11eb-9dd2-d28ffbac628b.png)
The releases was updated from yesterday, but the master branch was updated from 6 may

**Comment by landyrev** [comment]
@abner could you please push fix to the master? Build still failing when you try to install it from github repo

(I'm trying to make a PR, but I can't manage flutter_js being build from sources)
